/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum5;

import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class PesanMakanMinum extends javax.swing.JFrame {

    /**
     * Creates new form PesanMakanMinum
     */
    public PesanMakanMinum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cbNasiRames = new javax.swing.JCheckBox();
        cbNasiGoreng = new javax.swing.JCheckBox();
        cbEsTehManis = new javax.swing.JCheckBox();
        cbTehManisHangat = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfPorsiNasiRames = new javax.swing.JTextField();
        tfPorsiNasiGoreng = new javax.swing.JTextField();
        tfPorsiEsTehManis = new javax.swing.JTextField();
        tfPorsiTehManisHangat = new javax.swing.JTextField();
        tfJumlahNasiRames = new javax.swing.JTextField();
        tfJumlahNasiGoreng = new javax.swing.JTextField();
        tfJumlahEsTehManis = new javax.swing.JTextField();
        tfJumlahTehManisHangat = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnPesan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnBayar = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taView = new javax.swing.JTextArea();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jLabel11.setText("Pesanan Anda adalah");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Pesan Makan Minum");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Makanan & Minumanan");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Harga");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Porsi");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Jumlah");

        cbNasiRames.setText("Nasi Rames");
        cbNasiRames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNasiRamesActionPerformed(evt);
            }
        });

        cbNasiGoreng.setText("Nasi Goreng");

        cbEsTehManis.setText("Es Teh Manis");

        cbTehManisHangat.setText("Teh Manis Hangat");

        jLabel6.setText("Rp. 12.000");

        jLabel7.setText("Rp. 10.000");

        jLabel8.setText("Rp. 5.000");

        jLabel9.setText("Rp. 4.000");

        tfPorsiNasiRames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPorsiNasiRamesActionPerformed(evt);
            }
        });

        tfPorsiTehManisHangat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPorsiTehManisHangatActionPerformed(evt);
            }
        });

        tfJumlahNasiGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahNasiGorengActionPerformed(evt);
            }
        });

        btnPesan.setText("Pesan");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        jLabel10.setText("Total");

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel12.setText("Pesanan Anda adalah:");

        taView.setColumns(20);
        taView.setRows(5);
        jScrollPane3.setViewportView(taView);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(cbNasiGoreng, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbEsTehManis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(cbTehManisHangat))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbNasiRames, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(tfPorsiNasiRames, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfPorsiNasiGoreng, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfPorsiEsTehManis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfPorsiTehManisHangat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnPesan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfTotal)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfJumlahNasiRames)
                                    .addComponent(tfJumlahNasiGoreng)
                                    .addComponent(tfJumlahEsTehManis, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfJumlahTehManisHangat, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(16, 16, 16))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnBayar)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1)))
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNasiRames)
                    .addComponent(jLabel6)
                    .addComponent(tfPorsiNasiRames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJumlahNasiRames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNasiGoreng)
                    .addComponent(jLabel7)
                    .addComponent(tfPorsiNasiGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJumlahNasiGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEsTehManis)
                    .addComponent(jLabel8)
                    .addComponent(tfPorsiEsTehManis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJumlahEsTehManis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTehManisHangat)
                    .addComponent(jLabel9)
                    .addComponent(tfPorsiTehManisHangat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJumlahTehManisHangat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesan)
                    .addComponent(jLabel10)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnBayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbNasiRamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNasiRamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNasiRamesActionPerformed

    private void tfPorsiNasiRamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPorsiNasiRamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPorsiNasiRamesActionPerformed

    private void tfPorsiTehManisHangatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPorsiTehManisHangatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPorsiTehManisHangatActionPerformed

    private void tfJumlahNasiGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahNasiGorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJumlahNasiGorengActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        String tampil = "";
        int totalBiaya = 0;
        
        if (cbNasiRames.isSelected()) {
            int porsiNasiRames =
        Integer.parseInt(tfPorsiNasiRames.getText());
            int biayaNasiRames;
            
            biayaNasiRames = porsiNasiRames * 12000;
            tfJumlahNasiRames.setText("" + biayaNasiRames);
            
            totalBiaya += biayaNasiRames;
            
            tfTotal.setText("" + totalBiaya);
            tampil += cbNasiRames.getText() + " : Rp 12.000" + " x " +
        porsiNasiRames + " = " + biayaNasiRames + "\n";
        }
        if (cbNasiGoreng.isSelected()) {
            int porsiNasiGoreng =
        Integer.parseInt(tfPorsiNasiGoreng.getText());
            int biayaNasiGoreng;
            
            biayaNasiGoreng = porsiNasiGoreng * 10000;
            tfJumlahNasiGoreng.setText("" + biayaNasiGoreng);
            
            totalBiaya += biayaNasiGoreng;
            tfTotal.setText("" + totalBiaya);
        
            tampil += cbNasiGoreng.getText() + " : Rp 10.000" + " x " +
        porsiNasiGoreng + " = " + biayaNasiGoreng + "\n";
        }
        if (cbEsTehManis.isSelected()) {
            int porsiEsTehManis =
        Integer.parseInt(tfPorsiEsTehManis.getText());
            int biayaEsTehManis;
            
            biayaEsTehManis = porsiEsTehManis * 5000;
            tfJumlahNasiGoreng.setText("" + biayaEsTehManis);
            
            totalBiaya += biayaEsTehManis;
            tfTotal.setText("" + totalBiaya);
            
            tampil += cbEsTehManis.getText() + " : Rp 5.000" + " x " +
        porsiEsTehManis + " = " + biayaEsTehManis + "\n";
        }
        if (cbTehManisHangat.isSelected()) {
            int porsiTehManisHangat =
        Integer.parseInt(tfPorsiTehManisHangat.getText());
            int biayaTehManisHangat;
            
            biayaTehManisHangat = porsiTehManisHangat * 4000;
            tfJumlahTehManisHangat.setText("" + biayaTehManisHangat);
            
            totalBiaya += biayaTehManisHangat;
            tfTotal.setText("" + totalBiaya);
            
            tampil += cbTehManisHangat.getText() + " : Rp 4.000" + " x " +
        porsiTehManisHangat + " = " + biayaTehManisHangat + "\n";
        }
        
        taView.setText(tampil + "======================" + "\n" + "Total Bayar"
        + " \t: Rp. " + totalBiaya);
    }//GEN-LAST:event_btnBayarActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this,
                "Apakah Anda Ingin Keluar?",
                "Exit",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (jawab == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
        int totalBiaya = 0;
        if (cbNasiRames.isSelected()) {
            int porsiNasiRames =
        Integer.parseInt(tfPorsiNasiRames.getText());
            int biayaNasiRames;
            
            biayaNasiRames = porsiNasiRames * 12000;
            tfJumlahNasiRames.setText("" + biayaNasiRames);

            totalBiaya += biayaNasiRames;
            tfTotal.setText("" + totalBiaya);
        }
        if (cbNasiGoreng.isSelected()) {
            int porsiNasiGoreng =
        Integer.parseInt(tfPorsiNasiGoreng.getText());
            int biayaNasiGoreng;
            
            biayaNasiGoreng = porsiNasiGoreng * 10000;
            tfJumlahNasiGoreng.setText("" + biayaNasiGoreng);
            
            totalBiaya += biayaNasiGoreng;
            tfTotal.setText("" + totalBiaya);
        }
        if (cbEsTehManis.isSelected()) {
            int porsiEsTehManis =
        Integer.parseInt(tfPorsiEsTehManis.getText());
            int biayaEsTehManis;
            
            biayaEsTehManis = porsiEsTehManis * 5000;
            tfJumlahEsTehManis.setText("" + biayaEsTehManis);
            
            totalBiaya += biayaEsTehManis;
            tfTotal.setText("" + totalBiaya);
        }
        if (cbTehManisHangat.isSelected()) {
            int porsiTehManisHangat =
        Integer.parseInt(tfPorsiTehManisHangat.getText());
            int biayaTehManisHangat;
            
            biayaTehManisHangat = porsiTehManisHangat * 4000;
            tfJumlahTehManisHangat.setText("" + biayaTehManisHangat);
            
            totalBiaya += biayaTehManisHangat;
            tfTotal.setText("" + totalBiaya);
        }
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        cbNasiRames.setSelected(false);
        cbNasiGoreng.setSelected(false);
        cbEsTehManis.setSelected(false);
        cbTehManisHangat.setSelected(false);
        
        tfPorsiNasiRames.setText("");
        tfPorsiNasiGoreng.setText("");
        tfPorsiEsTehManis.setText("");
        tfPorsiTehManisHangat.setText("");
        
        tfJumlahNasiRames.setText("");
        tfJumlahNasiGoreng.setText("");
        tfJumlahEsTehManis.setText("");
        tfJumlahTehManisHangat.setText("");
        
        tfTotal.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        cbNasiRames.setSelected(false);
        cbNasiGoreng.setSelected(false);
        cbEsTehManis.setSelected(false);
        cbTehManisHangat.setSelected(false);
        
        tfPorsiNasiRames.setText("");
        tfPorsiNasiGoreng.setText("");
        tfPorsiEsTehManis.setText("");
        tfPorsiTehManisHangat.setText("");
        
        tfJumlahNasiRames.setText("");
        tfJumlahNasiGoreng.setText("");
        tfJumlahEsTehManis.setText("");
        tfJumlahTehManisHangat.setText("");
        
        tfTotal.setText("");
        taView.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesanMakanMinum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesanMakanMinum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesanMakanMinum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesanMakanMinum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesanMakanMinum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox cbEsTehManis;
    private javax.swing.JCheckBox cbNasiGoreng;
    private javax.swing.JCheckBox cbNasiRames;
    private javax.swing.JCheckBox cbTehManisHangat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea taView;
    private javax.swing.JTextField tfJumlahEsTehManis;
    private javax.swing.JTextField tfJumlahNasiGoreng;
    private javax.swing.JTextField tfJumlahNasiRames;
    private javax.swing.JTextField tfJumlahTehManisHangat;
    private javax.swing.JTextField tfPorsiEsTehManis;
    private javax.swing.JTextField tfPorsiNasiGoreng;
    private javax.swing.JTextField tfPorsiNasiRames;
    private javax.swing.JTextField tfPorsiTehManisHangat;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
